from . import res_users
from . import res_company
from . import res_city
from . import res_township
from . import res_religion
from . import res_country_state
from . import res_country
from . import res_partner
from . import account_move
from . import account_payment
from . import res_config_settings
from . import sale_order
from . import stock_move
from . import purchase_order_extend
