# -*- coding: utf-8 -*-
{
    'name': 'Base Setup',
    'version': '3.7',
    'summary': 'Base setup module.',
    'description': """
       Some of most used features in one module.
    """,
    'category': 'Setup',
    'website': "www.asiamatrixsoftware.com",
    'email': 'info@asiamatrixsoftware.com',
    'license': "LGPL-3",
    'depends': [
        'base',
        'sale',
        'contacts',
        'sale_stock',
        'purchase',
        'stock_account',
        'web',
    ],
    'data': [
        'security/res_groups.xml',
        'data/res_country.xml',
        'data/bill_credit_limit_data.xml',
        'security/ir.model.access.csv',
        'security/ir_rules.xml',
        'views/res_city_views.xml',
        'views/res_township_views.xml',
        'views/res_country_state_views.xml',
        'views/res_country_views.xml',
        'views/res_religion_views.xml',
        'views/res_company_views.xml',
        'views/res_partner_views.xml',
        'views/sale_views.xml',
        'views/purchase_views.xml',
        'views/account_move_views.xml',
        'views/res_users_views.xml',
        'views/res_config_settings_views.xml',
        'wizards/generate_partner_code_views.xml',
    ],
    "assets": {
        "web.assets_backend": ["ax_base_setup/static/src/js/form.js"],
        "web.assets_qweb": ["ax_base_setup/static/src/xml/FieldMany2One.xml"],
    },
    'installable': True,
    'application': False,
    'auto_install': False,
}
